plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'lib/omniauth-microsoft-identity2.rb'
    - 'tmp/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
    - 'lib/omniauth/strategies/microsoft_identity2.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/omniauth/strategies/microsoft_identity2.rb'
    - 'test/rails_integration_test.rb'
    - 'test/omniauth_microsoft_identity2_test.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
    - 'lib/omniauth/strategies/microsoft_identity2.rb'

Style/OneClassPerFile:
  Exclude:
    - 'test/rails_integration_test.rb'
    - 'lib/omniauth/strategies/microsoft_identity2.rb'

Minitest/MultipleAssertions:
  Exclude:
    - 'test/rails_integration_test.rb'
    - 'test/omniauth_microsoft_identity2_test.rb'
